version: "2"
run:
  tests: true
linters:
  enable:
    - misspell
    - revive
    - unconvert
  settings:
    revive:
      rules:
        - name: exported
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/conn-castle/agent-layer
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
