package install

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/conn-castle/agent-layer/internal/launchers"
	"github.com/conn-castle/agent-layer/internal/messages"
	"github.com/conn-castle/agent-layer/internal/templates"
)

func (inst *installer) scanUnknowns() error {
	known, err := inst.buildKnownPaths()
	if err != nil {
		return err
	}

	root := filepath.Join(inst.root, ".agent-layer")
	if err := inst.scanUnknownRoot(root, known); err != nil {
		return err
	}
	inst.sortUnknowns()
	return nil
}

func (inst *installer) scanUnknownRoot(root string, known map[string]struct{}) error {
	sys := inst.sys
	if _, err := sys.Stat(root); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return fmt.Errorf(messages.InstallFailedStatFmt, root, err)
	}
	return sys.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		clean := filepath.Clean(path)
		if clean == filepath.Clean(root) {
			return nil
		}
		if _, ok := known[clean]; ok {
			return nil
		}
		inst.recordUnknown(clean)
		if entry.IsDir() {
			return filepath.SkipDir
		}
		return nil
	})
}

func (inst *installer) handleUnknowns() error {
	if len(inst.unknowns) == 0 || !inst.overwrite {
		return nil
	}
	if inst.force {
		return inst.deleteUnknowns(inst.unknowns)
	}
	if inst.prompter == nil {
		return fmt.Errorf(messages.InstallDeleteUnknownPromptRequired)
	}
	rel := inst.relativeUnknowns()
	deleteAll, err := inst.prompter.DeleteUnknownAll(rel)
	if err != nil {
		return err
	}
	if deleteAll {
		return inst.deleteUnknowns(inst.unknowns)
	}
	for _, path := range inst.unknowns {
		relPath := inst.relativePath(path)
		deletePath, err := inst.prompter.DeleteUnknown(relPath)
		if err != nil {
			return err
		}
		if deletePath {
			if err := inst.sys.RemoveAll(path); err != nil {
				return fmt.Errorf(messages.InstallDeleteUnknownFailedFmt, relPath, err)
			}
		}
	}
	return nil
}

func (inst *installer) deleteUnknowns(paths []string) error {
	sys := inst.sys
	for _, path := range paths {
		rel := inst.relativePath(path)
		if err := sys.RemoveAll(path); err != nil {
			return fmt.Errorf(messages.InstallDeleteUnknownFailedFmt, rel, err)
		}
	}
	return nil
}

func (inst *installer) sortUnknowns() {
	sort.Slice(inst.unknowns, func(i, j int) bool {
		return inst.relativePath(inst.unknowns[i]) < inst.relativePath(inst.unknowns[j])
	})
}

func (inst *installer) relativeUnknowns() []string {
	if len(inst.unknowns) == 0 {
		return nil
	}
	rel := make([]string, 0, len(inst.unknowns))
	for _, path := range inst.unknowns {
		rel = append(rel, inst.relativePath(path))
	}
	sort.Strings(rel)
	return rel
}

func (inst *installer) buildKnownPaths() (map[string]struct{}, error) {
	known := make(map[string]struct{})
	add := func(path string) {
		known[filepath.Clean(path)] = struct{}{}
	}

	root := inst.root
	add(filepath.Join(root, ".agent-layer"))
	add(filepath.Join(root, ".agent-layer", "instructions"))
	add(filepath.Join(root, ".agent-layer", "slash-commands"))
	add(filepath.Join(root, ".agent-layer", "templates"))
	add(filepath.Join(root, ".agent-layer", "templates", "docs"))
	add(filepath.Join(root, ".agent-layer", "state"))
	add(filepath.Join(root, ".agent-layer", "state", "managed-baseline.json"))
	add(filepath.Join(root, ".agent-layer", "tmp"))
	add(filepath.Join(root, ".agent-layer", "tmp", "runs"))

	// Root-level managed files.
	for _, file := range inst.managedTemplateFiles() {
		add(file.path)
	}
	add(filepath.Join(root, ".agent-layer", "al.version"))

	// VS Code launchers generated by sync.
	for _, path := range launchers.VSCodePaths(root).All() {
		add(path)
	}

	addTemplatePaths := func(templateRoot string, destRoot string) error {
		return templates.Walk(templateRoot, func(path string, entry fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if entry.IsDir() {
				return nil
			}
			rel := strings.TrimPrefix(path, templateRoot+"/")
			if rel == path {
				return fmt.Errorf(messages.InstallUnexpectedTemplatePathFmt, path)
			}
			add(filepath.Join(destRoot, rel))
			return nil
		})
	}

	if err := addTemplatePaths("instructions", filepath.Join(root, ".agent-layer", "instructions")); err != nil {
		return nil, err
	}
	if err := addTemplatePaths("slash-commands", filepath.Join(root, ".agent-layer", "slash-commands")); err != nil {
		return nil, err
	}
	if err := addTemplatePaths("docs/agent-layer", filepath.Join(root, ".agent-layer", "templates", "docs")); err != nil {
		return nil, err
	}

	return known, nil
}
