package sync

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/conn-castle/agent-layer/internal/config"
	"github.com/conn-castle/agent-layer/internal/messages"
	"github.com/conn-castle/agent-layer/internal/projection"
)

// copilotMCPConfig mirrors the Copilot CLI mcp-config.json structure.
type copilotMCPConfig struct {
	Servers map[string]copilotMCPServer `json:"mcpServers"`
}

type copilotMCPServer struct {
	Type    string            `json:"type"`
	Command string            `json:"command,omitempty"`
	Args    []string          `json:"args,omitempty"`
	Env     map[string]string `json:"env,omitempty"`
	URL     string            `json:"url,omitempty"`
	Headers map[string]string `json:"headers,omitempty"`
	Tools   []string          `json:"tools,omitempty"`
}

// writeCopilotMCPConfig generates .copilot/mcp-config.json for GitHub Copilot CLI.
func writeCopilotMCPConfig(sys System, root string, project *config.ProjectConfig) error {
	cfg, err := buildCopilotMCPConfig(project)
	if err != nil {
		return err
	}

	data, err := sys.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf(messages.SyncMarshalCopilotMCPConfigFailedFmt, err)
	}
	data = append(data, '\n')

	copilotDir := filepath.Join(root, ".copilot")
	if err := sys.MkdirAll(copilotDir, 0o755); err != nil {
		return fmt.Errorf(messages.SyncCreateDirFailedFmt, copilotDir, err)
	}

	path := filepath.Join(copilotDir, "mcp-config.json")
	if err := sys.WriteFileAtomic(path, data, 0o644); err != nil {
		return fmt.Errorf(messages.SyncWriteFileFailedFmt, path, err)
	}

	return nil
}

func buildCopilotMCPConfig(project *config.ProjectConfig) (*copilotMCPConfig, error) {
	cfg := &copilotMCPConfig{
		Servers: make(map[string]copilotMCPServer),
	}

	resolved, err := projection.EffectiveMCPServers(
		project.Config,
		project.PlaceholderEnv(),
		projection.ClientCopilot,
		projection.ClientPlaceholderResolver("${%s}"),
	)
	if err != nil {
		return nil, err
	}

	for _, server := range resolved {
		entry := copilotMCPServer{
			Type:    server.Transport,
			Command: server.Command,
			Args:    server.Args,
			Env:     server.Env,
			URL:     server.URL,
			Headers: server.Headers,
			Tools:   []string{"*"},
		}
		cfg.Servers[server.ID] = entry
	}

	return cfg, nil
}

// cleanCopilotOutputs removes Copilot CLI artifacts generated by previous syncs.
// Call this when agents.copilot_cli is disabled so stale config does not persist.
func cleanCopilotOutputs(sys System, root string) error {
	mcpConfigPath := filepath.Join(root, ".copilot", "mcp-config.json")
	if err := sys.Remove(mcpConfigPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf(messages.SyncRemoveFailedFmt, mcpConfigPath, err)
	}
	return nil
}
