package sync

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/conn-castle/agent-layer/internal/config"
	"github.com/conn-castle/agent-layer/internal/messages"
	"github.com/conn-castle/agent-layer/internal/projection"
)

// copilotMCPConfig mirrors the Copilot CLI mcp-config.json structure.
type copilotMCPConfig struct {
	Servers OrderedMap[copilotMCPServer] `json:"mcpServers"`
}

type copilotMCPServer struct {
	Type    string             `json:"type"`
	Command string             `json:"command,omitempty"`
	Args    []string           `json:"args,omitempty"`
	Env     OrderedMap[string] `json:"env,omitempty"`
	URL     string             `json:"url,omitempty"`
	Headers OrderedMap[string] `json:"headers,omitempty"`
	Tools   []string           `json:"tools,omitempty"`
}

// WriteCopilotMCPConfig generates .copilot/mcp-config.json for GitHub Copilot CLI.
// Contains external MCP servers only.
func WriteCopilotMCPConfig(sys System, root string, project *config.ProjectConfig) error {
	cfg, err := buildCopilotMCPConfig(project)
	if err != nil {
		return err
	}

	data, err := sys.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf(messages.SyncMarshalCopilotMCPConfigFailedFmt, err)
	}
	data = append(data, '\n')

	copilotDir := filepath.Join(root, ".copilot")
	if err := sys.MkdirAll(copilotDir, 0o755); err != nil {
		return fmt.Errorf(messages.SyncCreateDirFailedFmt, copilotDir, err)
	}

	path := filepath.Join(copilotDir, "mcp-config.json")
	if err := sys.WriteFileAtomic(path, data, 0o644); err != nil {
		return fmt.Errorf(messages.SyncWriteFileFailedFmt, path, err)
	}

	return nil
}

func buildCopilotMCPConfig(project *config.ProjectConfig) (*copilotMCPConfig, error) {
	cfg := &copilotMCPConfig{
		Servers: make(OrderedMap[copilotMCPServer]),
	}

	resolved, err := projection.ResolveMCPServers(
		project.Config.MCP.Servers,
		project.Env,
		"copilot",
		projection.ClientPlaceholderResolver("${%s}"),
	)
	if err != nil {
		return nil, err
	}

	for _, server := range resolved {
		entry := copilotMCPServer{
			Type:    server.Transport,
			Command: server.Command,
			Args:    server.Args,
			URL:     server.URL,
			Tools:   []string{"*"},
		}
		if len(server.Headers) > 0 {
			headers := make(OrderedMap[string], len(server.Headers))
			for key, value := range server.Headers {
				headers[key] = value
			}
			entry.Headers = headers
		}
		if len(server.Env) > 0 {
			envMap := make(OrderedMap[string], len(server.Env))
			for key, value := range server.Env {
				envMap[key] = value
			}
			entry.Env = envMap
		}
		cfg.Servers[server.ID] = entry
	}

	return cfg, nil
}

// CleanCopilotOutputs removes Copilot CLI artifacts generated by previous syncs.
// Call this when agents.copilot_cli is disabled so stale config does not persist.
func CleanCopilotOutputs(sys System, root string) error {
	mcpConfigPath := filepath.Join(root, ".copilot", "mcp-config.json")
	if err := sys.Remove(mcpConfigPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf(messages.SyncRemoveFailedFmt, mcpConfigPath, err)
	}
	return nil
}
