package sync

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	yaml "go.yaml.in/yaml/v3"

	"github.com/conn-castle/agent-layer/internal/config"
	"github.com/conn-castle/agent-layer/internal/messages"
)

const promptHeaderTemplate = "<!--\n  GENERATED FILE\n  Source: %s\n  Regenerate: al sync\n-->\n"

const (
	generatedMarkerHeader     = "GENERATED FILE"
	generatedMarkerSource     = "Source: .agent-layer/"
	generatedMarkerRegenerate = "Regenerate: al sync"
)

// skillContentBuilder builds skill file content for a skill.
type skillContentBuilder func(cmd config.Skill) (string, error)

// writeSkillFiles generates skill files in the specified directory using the provided content builder.
// After writing each SKILL.md, it reconciles any subdirectory files (scripts/, references/, assets/)
// from the source skill directory to support the Agent Skills spec's on-demand resource loading.
func writeSkillFiles(sys System, skillsDir string, commands []config.Skill, buildContent skillContentBuilder) error {
	if err := sys.MkdirAll(skillsDir, 0o755); err != nil {
		return fmt.Errorf(messages.SyncCreateDirFailedFmt, skillsDir, err)
	}

	wanted := make(map[string]struct{}, len(commands))
	for _, cmd := range commands {
		if strings.Contains(cmd.Name, "..") || strings.ContainsAny(cmd.Name, `/\`) {
			return fmt.Errorf("invalid skill name %q: must not contain path separators or '..'", cmd.Name)
		}
		skillDir := filepath.Join(skillsDir, cmd.Name)
		path := filepath.Join(skillDir, "SKILL.md")
		content, err := buildContent(cmd)
		if err != nil {
			return fmt.Errorf(messages.SyncWriteFileFailedFmt, path, err)
		}

		wanted[cmd.Name] = struct{}{}
		skillInfo, lstatErr := sys.Lstat(skillDir)
		if lstatErr != nil && !os.IsNotExist(lstatErr) {
			return fmt.Errorf(messages.SyncReadFailedFmt, skillDir, lstatErr)
		}
		if lstatErr == nil && skillInfo.Mode()&os.ModeSymlink != 0 {
			if err := removeSkillResourceNode(sys, skillDir, skillInfo); err != nil {
				return err
			}
		}
		if err := sys.MkdirAll(skillDir, 0o755); err != nil {
			return fmt.Errorf(messages.SyncCreateDirFailedFmt, skillDir, err)
		}
		if err := sys.WriteFileAtomic(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf(messages.SyncWriteFileFailedFmt, path, err)
		}
		if err := copySkillSubFiles(sys, cmd, skillDir); err != nil {
			return err
		}
	}

	return removeStaleSkillDirs(sys, skillsDir, wanted)
}

// copySkillSubFiles reconciles non-SKILL.md files from the skill's source directory into destDir.
// This enables agents to access scripts/, references/, and assets/ via their native file-read tools.
// Skips SKILL.md/skill.md at the top level (already generated by the content builder) and hidden files.
func copySkillSubFiles(sys System, skill config.Skill, destDir string) error {
	skipFiles := map[string]struct{}{
		"SKILL.md": {},
		"skill.md": {},
	}
	return copyDirRecursive(sys, skill.SourceDir, destDir, skipFiles)
}

type desiredSkillResource struct {
	isDir bool
	data  []byte
	mode  os.FileMode
}

// copyDirRecursive reconciles the contents of srcDir into destDir: it materializes
// every non-hidden, non-symlink source entry under destDir (handling file<->directory
// type transitions) and deletes any destination entry that is absent from the source.
// When skipFiles contains "SKILL.md", the top-level destination SKILL.md is preserved
// and never deleted as stale, since the content builder owns that file. skipFiles
// names are skipped only at the top level of srcDir.
func copyDirRecursive(sys System, srcDir string, destDir string, skipFiles map[string]struct{}) error {
	desired := make(map[string]desiredSkillResource)
	if srcDir != "" {
		if err := collectDesiredSkillResources(sys, srcDir, "", skipFiles, desired); err != nil {
			return err
		}
	}

	paths := make([]string, 0, len(desired))
	for path := range desired {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, relativePath := range paths {
		resource := desired[relativePath]
		destPath := filepath.Join(destDir, relativePath)
		destInfo, err := sys.Lstat(destPath)
		if err != nil && !os.IsNotExist(err) {
			return fmt.Errorf(messages.SyncReadFailedFmt, destPath, err)
		}
		if err == nil && (destInfo.IsDir() != resource.isDir || destInfo.Mode()&os.ModeSymlink != 0) {
			if err := removeSkillResourceNode(sys, destPath, destInfo); err != nil {
				return err
			}
		}

		if resource.isDir {
			if err := sys.MkdirAll(destPath, 0o755); err != nil {
				return fmt.Errorf(messages.SyncCreateDirFailedFmt, destPath, err)
			}
			continue
		}
		if err := sys.WriteFileAtomic(destPath, resource.data, resource.mode); err != nil {
			return fmt.Errorf(messages.SyncWriteFileFailedFmt, destPath, err)
		}
	}

	_, preserveCanonicalSkill := skipFiles["SKILL.md"]
	return removeStaleSkillResources(sys, destDir, "", desired, preserveCanonicalSkill)
}

// collectDesiredSkillResources recursively walks srcDir and records every desired
// resource in desired, keyed by path relative to the original source root:
// directories as markers and files with their bytes and mode. It skips hidden
// entries, symlinks, and (only at the top level) names in skipFiles. A missing
// srcDir contributes no entries; any other read error is returned wrapped with
// SyncReadFailedFmt.
func collectDesiredSkillResources(
	sys System,
	srcDir string,
	relativeDir string,
	skipFiles map[string]struct{},
	desired map[string]desiredSkillResource,
) error {
	entries, err := sys.ReadDir(srcDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf(messages.SyncReadFailedFmt, srcDir, err)
	}

	for _, entry := range entries {
		name := entry.Name()
		if strings.HasPrefix(name, ".") {
			continue
		}
		if _, skip := skipFiles[name]; skip {
			continue
		}

		srcPath := filepath.Join(srcDir, name)
		relativePath := filepath.Join(relativeDir, name)
		srcInfo, err := sys.Lstat(srcPath)
		if err != nil {
			return fmt.Errorf(messages.SyncReadFailedFmt, srcPath, err)
		}
		if srcInfo.Mode()&os.ModeSymlink != 0 {
			continue
		}

		if srcInfo.IsDir() {
			desired[relativePath] = desiredSkillResource{isDir: true}
			if err := collectDesiredSkillResources(sys, srcPath, relativePath, nil, desired); err != nil {
				return err
			}
			continue
		}

		data, err := sys.ReadFile(srcPath)
		if err != nil {
			return fmt.Errorf(messages.SyncReadFailedFmt, srcPath, err)
		}
		desired[relativePath] = desiredSkillResource{data: data, mode: srcInfo.Mode()}
	}
	return nil
}

// removeStaleSkillResources recursively walks the destDir subtree rooted at
// relativeDir and removes every entry not present in desired, recursing into
// directories that are themselves desired. When preserveCanonicalSkill is true,
// the top-level SKILL.md is kept even though it is never part of desired.
func removeStaleSkillResources(
	sys System,
	destDir string,
	relativeDir string,
	desired map[string]desiredSkillResource,
	preserveCanonicalSkill bool,
) error {
	currentDir := filepath.Join(destDir, relativeDir)
	entries, err := sys.ReadDir(currentDir)
	if err != nil {
		return fmt.Errorf(messages.SyncReadFailedFmt, currentDir, err)
	}

	for _, entry := range entries {
		name := entry.Name()
		if relativeDir == "" && preserveCanonicalSkill && strings.EqualFold(name, "SKILL.md") {
			continue
		}

		relativePath := filepath.Join(relativeDir, name)
		if resource, ok := desired[relativePath]; ok {
			if resource.isDir {
				if err := removeStaleSkillResources(sys, destDir, relativePath, desired, false); err != nil {
					return err
				}
			}
			continue
		}

		destPath := filepath.Join(destDir, relativePath)
		info, err := sys.Lstat(destPath)
		if err != nil {
			return fmt.Errorf(messages.SyncReadFailedFmt, destPath, err)
		}
		if err := removeSkillResourceNode(sys, destPath, info); err != nil {
			return err
		}
	}
	return nil
}

// removeSkillResourceNode removes a single destination node: RemoveAll for a
// directory, Remove for a file or symlink (which unlinks the symlink itself
// rather than following it). Failures are wrapped with SyncRemoveFailedFmt.
func removeSkillResourceNode(sys System, path string, info os.FileInfo) error {
	var err error
	if info.IsDir() {
		err = sys.RemoveAll(path)
	} else {
		err = sys.Remove(path)
	}
	if err != nil {
		return fmt.Errorf(messages.SyncRemoveFailedFmt, path, err)
	}
	return nil
}

// writeAgentSkills generates shared Agent Skills in .agents/skills/<name>/SKILL.md.
func writeAgentSkills(sys System, root string, commands []config.Skill) error {
	skillsDir := filepath.Join(root, ".agents", "skills")
	return writeSkillFiles(sys, skillsDir, commands, buildAgentSkill)
}

// writeClaudeSkills generates Claude Code skill files in .claude/skills/<name>/SKILL.md.
func writeClaudeSkills(sys System, root string, commands []config.Skill) error {
	skillsDir := filepath.Join(root, ".claude", "skills")
	return writeSkillFiles(sys, skillsDir, commands, buildClaudeSkill)
}

// buildAgentSkill returns portable Agent Skills SKILL.md content.
func buildAgentSkill(cmd config.Skill) (string, error) {
	var builder strings.Builder
	frontMatter, err := buildSkillFrontMatter(cmd)
	if err != nil {
		return "", err
	}
	builder.WriteString(frontMatter)
	fmt.Fprintf(&builder, promptHeaderTemplate, generatedSkillSourcePath(cmd))
	if cmd.Body != "" {
		builder.WriteString("\n")
		builder.WriteString(cmd.Body)
		if !strings.HasSuffix(cmd.Body, "\n") {
			builder.WriteString("\n")
		}
	}
	return builder.String(), nil
}

// buildClaudeSkill returns the Claude Code SKILL.md content.
// Uses the standard agentskills.io format: YAML frontmatter + body.
func buildClaudeSkill(cmd config.Skill) (string, error) {
	return buildAgentSkill(cmd)
}

func buildSkillFrontMatter(cmd config.Skill) (string, error) {
	root := &yaml.Node{Kind: yaml.MappingNode}
	appendFrontMatterScalar(root, "name", strings.TrimSpace(cmd.Name))
	appendFrontMatterDescription(root, strings.TrimSpace(cmd.Description))
	appendFrontMatterOptionalScalar(root, "license", strings.TrimSpace(cmd.License))
	appendFrontMatterOptionalScalar(root, "compatibility", strings.TrimSpace(cmd.Compatibility))
	appendFrontMatterMetadata(root, copyMetadata(cmd.Metadata))
	appendFrontMatterOptionalScalar(root, "allowed-tools", strings.TrimSpace(cmd.AllowedTools))

	var yamlBody strings.Builder
	encoder := yaml.NewEncoder(&yamlBody)
	encoder.SetIndent(2)
	if err := encoder.Encode(root); err != nil {
		return "", err
	}
	if err := encoder.Close(); err != nil {
		return "", err
	}

	var frontMatter strings.Builder
	frontMatter.WriteString("---\n")
	frontMatter.WriteString(strings.TrimSuffix(yamlBody.String(), "\n"))
	frontMatter.WriteString("\n---\n\n")
	return frontMatter.String(), nil
}

func appendFrontMatterScalar(root *yaml.Node, key string, value string) {
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key},
		&yaml.Node{Kind: yaml.ScalarNode, Value: value},
	)
}

func appendFrontMatterDescription(root *yaml.Node, description string) {
	style := yaml.FoldedStyle
	if strings.Contains(description, "\n") {
		style = yaml.LiteralStyle
	}
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "description"},
		&yaml.Node{Kind: yaml.ScalarNode, Value: description, Style: style},
	)
}

func appendFrontMatterOptionalScalar(root *yaml.Node, key string, value string) {
	if value == "" {
		return
	}
	appendFrontMatterScalar(root, key, value)
}

func appendFrontMatterMetadata(root *yaml.Node, metadata map[string]string) {
	if len(metadata) == 0 {
		return
	}
	keys := make([]string, 0, len(metadata))
	for key := range metadata {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	metadataNode := &yaml.Node{Kind: yaml.MappingNode}
	for _, key := range keys {
		metadataNode.Content = append(metadataNode.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: key},
			&yaml.Node{Kind: yaml.ScalarNode, Value: metadata[key]},
		)
	}
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "metadata"},
		metadataNode,
	)
}

func copyMetadata(metadata map[string]string) map[string]string {
	if len(metadata) == 0 {
		return nil
	}
	normalized := make(map[string]string, len(metadata))
	for key, value := range metadata {
		normalized[key] = value
	}
	return normalized
}

func generatedSkillSourcePath(cmd config.Skill) string {
	defaultPath := filepath.ToSlash(filepath.Join(".agent-layer", "skills", cmd.Name, "SKILL.md"))
	source := strings.TrimSpace(cmd.SourcePath)
	if source == "" {
		return defaultPath
	}
	normalized := filepath.ToSlash(source)
	if strings.HasPrefix(normalized, ".agent-layer/") {
		return normalized
	}
	marker := "/.agent-layer/"
	if idx := strings.Index(normalized, marker); idx >= 0 {
		return normalized[idx+1:]
	}
	return defaultPath
}

func removeStaleSkillDirs(sys System, skillsDir string, wanted map[string]struct{}) error {
	entries, err := sys.ReadDir(skillsDir)
	if err != nil {
		return fmt.Errorf(messages.SyncReadFailedFmt, skillsDir, err)
	}

	var stale []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		if _, ok := wanted[name]; ok {
			continue
		}
		skillPath := filepath.Join(skillsDir, name, "SKILL.md")
		isGenerated, err := hasGeneratedMarker(sys, skillPath)
		if err != nil {
			return err
		}
		if isGenerated {
			stale = append(stale, filepath.Join(skillsDir, name))
		}
	}

	sort.Strings(stale)
	for _, dir := range stale {
		if err := sys.RemoveAll(dir); err != nil {
			return fmt.Errorf(messages.SyncRemoveFailedFmt, dir, err)
		}
	}

	return nil
}

// cleanSharedAgentSkills removes generated .agents/skills entries when no shared-skill consumer is enabled.
func cleanSharedAgentSkills(sys System, root string) error {
	skillsDir := filepath.Join(root, ".agents", "skills")
	if _, err := sys.ReadDir(skillsDir); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf(messages.SyncReadFailedFmt, skillsDir, err)
	}
	return removeStaleSkillDirs(sys, skillsDir, map[string]struct{}{})
}

// cleanLegacySkillOutputs removes retired Agent Layer-generated skill
// projection directories. Agent Layer claims exclusive ownership of these
// paths (see docs/SKILL-CLIENT-SPEC.md "Ownership of legacy projection
// paths") and removes them unconditionally. The canonical list lives in
// config.LegacySkillProjections.
func cleanLegacySkillOutputs(sys System, root string) error {
	for _, projection := range config.LegacySkillProjections {
		path := filepath.Join(append([]string{root}, projection.Dir...)...)
		if err := sys.RemoveAll(path); err != nil {
			return fmt.Errorf(messages.SyncRemoveFailedFmt, path, err)
		}
	}
	return nil
}

func hasGeneratedMarker(sys System, path string) (bool, error) {
	data, err := sys.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf(messages.SyncReadFailedFmt, path, err)
	}
	content := string(data)
	return strings.Contains(content, generatedMarkerHeader) &&
		strings.Contains(content, generatedMarkerSource) &&
		strings.Contains(content, generatedMarkerRegenerate), nil
}
