package sync

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	yaml "go.yaml.in/yaml/v3"

	"github.com/conn-castle/agent-layer/internal/config"
	"github.com/conn-castle/agent-layer/internal/messages"
)

const promptHeaderTemplate = "<!--\n  GENERATED FILE\n  Source: %s\n  Regenerate: al sync\n-->\n"

const (
	generatedMarkerHeader     = "GENERATED FILE"
	generatedMarkerSource     = "Source: .agent-layer/"
	generatedMarkerRegenerate = "Regenerate: al sync"
)

// skillContentBuilder builds skill file content for a skill.
type skillContentBuilder func(cmd config.Skill) (string, error)

// writeSkillFiles generates skill files in the specified directory using the provided content builder.
// After writing each SKILL.md, it copies any subdirectory files (scripts/, references/, assets/)
// from the source skill directory to support the Agent Skills spec's on-demand resource loading.
func writeSkillFiles(sys System, skillsDir string, commands []config.Skill, buildContent skillContentBuilder) error {
	if err := sys.MkdirAll(skillsDir, 0o755); err != nil {
		return fmt.Errorf(messages.SyncCreateDirFailedFmt, skillsDir, err)
	}

	wanted := make(map[string]struct{}, len(commands))
	for _, cmd := range commands {
		if strings.Contains(cmd.Name, "..") || strings.ContainsAny(cmd.Name, `/\`) {
			return fmt.Errorf("invalid skill name %q: must not contain path separators or '..'", cmd.Name)
		}
		wanted[cmd.Name] = struct{}{}
		skillDir := filepath.Join(skillsDir, cmd.Name)
		if err := sys.RemoveAll(skillDir); err != nil {
			return fmt.Errorf(messages.SyncRemoveFailedFmt, skillDir, err)
		}
		if err := sys.MkdirAll(skillDir, 0o755); err != nil {
			return fmt.Errorf(messages.SyncCreateDirFailedFmt, skillDir, err)
		}
		path := filepath.Join(skillDir, "SKILL.md")
		content, err := buildContent(cmd)
		if err != nil {
			return fmt.Errorf(messages.SyncWriteFileFailedFmt, path, err)
		}
		if err := sys.WriteFileAtomic(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf(messages.SyncWriteFileFailedFmt, path, err)
		}
		if err := copySkillSubFiles(sys, cmd, skillDir); err != nil {
			return err
		}
	}

	return removeStaleSkillDirs(sys, skillsDir, wanted)
}

// copySkillSubFiles copies non-SKILL.md files from the skill's source directory to destDir.
// This enables agents to access scripts/, references/, and assets/ via their native file-read tools.
// Skips SKILL.md/skill.md at the top level (already generated by the content builder) and hidden files.
func copySkillSubFiles(sys System, skill config.Skill, destDir string) error {
	if skill.SourceDir == "" {
		return nil
	}

	skipFiles := map[string]struct{}{
		"SKILL.md": {},
		"skill.md": {},
	}
	return copyDirRecursive(sys, skill.SourceDir, destDir, skipFiles)
}

// copyDirRecursive copies files from srcDir to destDir, skipping hidden entries and symlinks.
// skipFiles contains filenames to skip (applied only at the current directory level).
func copyDirRecursive(sys System, srcDir string, destDir string, skipFiles map[string]struct{}) error {
	entries, err := sys.ReadDir(srcDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf(messages.SyncReadFailedFmt, srcDir, err)
	}

	for _, entry := range entries {
		name := entry.Name()
		if strings.HasPrefix(name, ".") {
			continue
		}
		if entry.Type()&fs.ModeSymlink != 0 {
			continue
		}
		if _, skip := skipFiles[name]; skip {
			continue
		}

		srcPath := filepath.Join(srcDir, name)
		destPath := filepath.Join(destDir, name)

		if entry.IsDir() {
			if err := sys.MkdirAll(destPath, 0o755); err != nil {
				return fmt.Errorf(messages.SyncCreateDirFailedFmt, destPath, err)
			}
			if err := copyDirRecursive(sys, srcPath, destPath, nil); err != nil {
				return err
			}
			continue
		}

		data, err := sys.ReadFile(srcPath)
		if err != nil {
			return fmt.Errorf(messages.SyncReadFailedFmt, srcPath, err)
		}
		srcInfo, err := sys.Stat(srcPath)
		if err != nil {
			return fmt.Errorf(messages.SyncReadFailedFmt, srcPath, err)
		}
		if err := sys.WriteFileAtomic(destPath, data, srcInfo.Mode()); err != nil {
			return fmt.Errorf(messages.SyncWriteFileFailedFmt, destPath, err)
		}
	}
	return nil
}

// WriteAgentSkills generates shared Agent Skills in .agents/skills/<name>/SKILL.md.
func WriteAgentSkills(sys System, root string, commands []config.Skill) error {
	skillsDir := filepath.Join(root, ".agents", "skills")
	return writeSkillFiles(sys, skillsDir, commands, buildAgentSkill)
}

// WriteClaudeSkills generates Claude Code skill files in .claude/skills/<name>/SKILL.md.
func WriteClaudeSkills(sys System, root string, commands []config.Skill) error {
	skillsDir := filepath.Join(root, ".claude", "skills")
	return writeSkillFiles(sys, skillsDir, commands, buildClaudeSkill)
}

// buildAgentSkill returns portable Agent Skills SKILL.md content.
func buildAgentSkill(cmd config.Skill) (string, error) {
	var builder strings.Builder
	frontMatter, err := buildSkillFrontMatter(cmd)
	if err != nil {
		return "", err
	}
	builder.WriteString(frontMatter)
	fmt.Fprintf(&builder, promptHeaderTemplate, generatedSkillSourcePath(cmd))
	if cmd.Body != "" {
		builder.WriteString("\n")
		builder.WriteString(cmd.Body)
		if !strings.HasSuffix(cmd.Body, "\n") {
			builder.WriteString("\n")
		}
	}
	return builder.String(), nil
}

// buildClaudeSkill returns the Claude Code SKILL.md content.
// Uses the standard agentskills.io format: YAML frontmatter + body.
func buildClaudeSkill(cmd config.Skill) (string, error) {
	return buildAgentSkill(cmd)
}

func buildSkillFrontMatter(cmd config.Skill) (string, error) {
	root := &yaml.Node{Kind: yaml.MappingNode}
	appendFrontMatterScalar(root, "name", strings.TrimSpace(cmd.Name))
	appendFrontMatterDescription(root, strings.TrimSpace(cmd.Description))
	appendFrontMatterOptionalScalar(root, "license", strings.TrimSpace(cmd.License))
	appendFrontMatterOptionalScalar(root, "compatibility", strings.TrimSpace(cmd.Compatibility))
	appendFrontMatterMetadata(root, copyMetadata(cmd.Metadata))
	appendFrontMatterOptionalScalar(root, "allowed-tools", strings.TrimSpace(cmd.AllowedTools))

	var yamlBody strings.Builder
	encoder := yaml.NewEncoder(&yamlBody)
	encoder.SetIndent(2)
	if err := encoder.Encode(root); err != nil {
		return "", err
	}
	if err := encoder.Close(); err != nil {
		return "", err
	}

	var frontMatter strings.Builder
	frontMatter.WriteString("---\n")
	frontMatter.WriteString(strings.TrimSuffix(yamlBody.String(), "\n"))
	frontMatter.WriteString("\n---\n\n")
	return frontMatter.String(), nil
}

func appendFrontMatterScalar(root *yaml.Node, key string, value string) {
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key},
		&yaml.Node{Kind: yaml.ScalarNode, Value: value},
	)
}

func appendFrontMatterDescription(root *yaml.Node, description string) {
	style := yaml.FoldedStyle
	if strings.Contains(description, "\n") {
		style = yaml.LiteralStyle
	}
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "description"},
		&yaml.Node{Kind: yaml.ScalarNode, Value: description, Style: style},
	)
}

func appendFrontMatterOptionalScalar(root *yaml.Node, key string, value string) {
	if value == "" {
		return
	}
	appendFrontMatterScalar(root, key, value)
}

func appendFrontMatterMetadata(root *yaml.Node, metadata map[string]string) {
	if len(metadata) == 0 {
		return
	}
	keys := make([]string, 0, len(metadata))
	for key := range metadata {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	metadataNode := &yaml.Node{Kind: yaml.MappingNode}
	for _, key := range keys {
		metadataNode.Content = append(metadataNode.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: key},
			&yaml.Node{Kind: yaml.ScalarNode, Value: metadata[key]},
		)
	}
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "metadata"},
		metadataNode,
	)
}

func copyMetadata(metadata map[string]string) map[string]string {
	if len(metadata) == 0 {
		return nil
	}
	normalized := make(map[string]string, len(metadata))
	for key, value := range metadata {
		normalized[key] = value
	}
	return normalized
}

func generatedSkillSourcePath(cmd config.Skill) string {
	defaultPath := filepath.ToSlash(filepath.Join(".agent-layer", "skills", cmd.Name, "SKILL.md"))
	source := strings.TrimSpace(cmd.SourcePath)
	if source == "" {
		return defaultPath
	}
	normalized := filepath.ToSlash(source)
	if strings.HasPrefix(normalized, ".agent-layer/") {
		return normalized
	}
	marker := "/.agent-layer/"
	if idx := strings.Index(normalized, marker); idx >= 0 {
		return normalized[idx+1:]
	}
	return defaultPath
}

func removeStaleSkillDirs(sys System, skillsDir string, wanted map[string]struct{}) error {
	entries, err := sys.ReadDir(skillsDir)
	if err != nil {
		return fmt.Errorf(messages.SyncReadFailedFmt, skillsDir, err)
	}

	var stale []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		if _, ok := wanted[name]; ok {
			continue
		}
		skillPath := filepath.Join(skillsDir, name, "SKILL.md")
		isGenerated, err := hasGeneratedMarker(sys, skillPath)
		if err != nil {
			return err
		}
		if isGenerated {
			stale = append(stale, filepath.Join(skillsDir, name))
		}
	}

	sort.Strings(stale)
	for _, dir := range stale {
		if err := sys.RemoveAll(dir); err != nil {
			return fmt.Errorf(messages.SyncRemoveFailedFmt, dir, err)
		}
	}

	return nil
}

// CleanSharedAgentSkills removes generated .agents/skills entries when no shared-skill consumer is enabled.
func CleanSharedAgentSkills(sys System, root string) error {
	skillsDir := filepath.Join(root, ".agents", "skills")
	if _, err := sys.ReadDir(skillsDir); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf(messages.SyncReadFailedFmt, skillsDir, err)
	}
	return removeStaleSkillDirs(sys, skillsDir, map[string]struct{}{})
}

// CleanLegacySkillOutputs removes retired Agent Layer-generated skill
// projection directories. Agent Layer claims exclusive ownership of these
// paths (see docs/SKILL-CLIENT-SPEC.md "Ownership of legacy projection
// paths") and removes them unconditionally. The canonical list lives in
// config.LegacySkillProjections.
func CleanLegacySkillOutputs(sys System, root string) error {
	for _, projection := range config.LegacySkillProjections {
		path := filepath.Join(append([]string{root}, projection.Dir...)...)
		if err := sys.RemoveAll(path); err != nil {
			return fmt.Errorf(messages.SyncRemoveFailedFmt, path, err)
		}
	}
	return nil
}

func hasGeneratedMarker(sys System, path string) (bool, error) {
	data, err := sys.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf(messages.SyncReadFailedFmt, path, err)
	}
	content := string(data)
	return strings.Contains(content, generatedMarkerHeader) &&
		strings.Contains(content, generatedMarkerSource) &&
		strings.Contains(content, generatedMarkerRegenerate), nil
}
